bugfix: error when I execute "./build-libmongod-32bit.sh":
make libmongod
std.stdarg is deprecated. You should import core.vararg instead.
src/mongod/mongo.d(69): Error: core.thread.memcpy at /usr/bin/../src/druntime/import/core/thread.di(48) conflicts with core.stdc.string.memcpy at /usr/bin/../src/druntime/import/core/stdc/string.di(11)
src/mongod/mongo.d(69): Error: function core.thread.memcpy is not accessible from module mongo
src/mongod/mongo.d(128): Error: core.thread.memcpy at /usr/bin/../src/druntime/import/core/thread.di(48) conflicts with core.stdc.string.memcpy at /usr/bin/../src/druntime/import/core/stdc/string.di(11)
src/mongod/mongo.d(128): Error: function core.thread.memcpy is not accessible from module mongo
make example
export/mongod/md5.di(9): use of typedef is deprecated; use alias instead
export/mongod/md5.di(9): use of typedef is deprecated; use alias instead
export/mongod/md5.di(11): use of typedef is deprecated; use alias instead
export/mongod/md5.di(11): use of typedef is deprecated; use alias instead